apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mldev-namespace-admin
  namespace: mldev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:mldev-namespace-admin
