apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-lima-namespace-admin
  namespace: project-lima
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:project-lima-namespace-admin
