apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: smoke-test-namespace-admin
  namespace: smoke-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:smoke-test-namespace-admin
